version: '3.9'
# Defining the compose version
services:

 # Nginx server
  nginx:
 
    # Build context
    #  build: ./nginx
    image: niginx-final:v0.0.1
    
    # Mapping machine and container ports
    ports:
      - 1337:80
      
    # Storage volumes
    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - web
    env_file:
      - .env/prod.env
    restart: "on-failure"
   
 # Django application
  web:
  
    # Build context
    # build: ./web
    image: python-final:v0.0.3
    
    # Build commands
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py collectstatic &&
                    gunicorn web.wsgi:application --bind 0.0.0.0:8000"
                    
    # Storage volumes
    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media
      
    # Exposing port 8000
    expose: 
      - 8000
    env_file:
      - .env/prod.env
    restart: "on-failure"
volumes:
  postgres_data:
  static_volume:
  media_volume: