# Generated by Django 4.1.7 on 2023-02-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RFP", "0002_document_usercopy_doc_index_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="document_usercopy", name="user",),
        migrations.AddField(
            model_name="document_usercopy",
            name="user",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
