# Generated by Django 3.1.2 on 2023-03-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0005_auto_20230312_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentapproval',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, choices=[('Healthcare', 'Healthcare'), ('Agnostic', 'Agnostic'), ('HigherEducation', 'Higher Education'), ('Finanace', 'Finanace')], default='Agnostic', max_length=100, null=True),
        ),
    ]
