# Generated by Django 3.2 on 2023-03-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0007_auto_20230313_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='rfpdata',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rfpid', models.CharField(blank=True, max_length=50, null=True)),
                ('rfp_resource_name', models.TextField(blank=True, max_length=50, null=True)),
                ('industry', models.TextField(blank=True, max_length=50, null=True)),
                ('country', models.TextField(blank=True, max_length=50, null=True)),
                ('section', models.TextField(blank=True, max_length=50, null=True)),
                ('question', models.CharField(blank=True, max_length=50, null=True)),
                ('document_ink', models.CharField(blank=True, max_length=50, null=True)),
                ('image_link', models.CharField(blank=True, max_length=50, null=True)),
                ('content_type', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rfpsection',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rfpid', models.CharField(blank=True, max_length=50, null=True)),
                ('conten_type', models.TextField(blank=True, max_length=50, null=True)),
                ('industry', models.TextField(blank=True, max_length=50, null=True)),
                ('country', models.TextField(blank=True, max_length=50, null=True)),
                ('section', models.TextField(blank=True, max_length=50, null=True)),
                ('sub_section', models.TextField(blank=True, max_length=50, null=True)),
                ('question', models.CharField(blank=True, max_length=50, null=True)),
                ('document_Link', models.CharField(blank=True, max_length=50, null=True)),
                ('image_link', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='./media/'),
        ),
        migrations.AlterField(
            model_name='askques',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='first_page',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, choices=[('Healthcare', 'Healthcare'), ('HigherEducation', 'Higher Education'), ('Finanace', 'Finanace'), ('Agnostic', 'Agnostic')], default='Agnostic', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='info',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kpmgadd',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
