# Generated by Django 3.2 on 2023-03-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0008_auto_20230325_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfpdata',
            old_name='section',
            new_name='section_data',
        ),
        migrations.RenameField(
            model_name='rfpsection',
            old_name='section',
            new_name='section_data',
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, choices=[('Healthcare', 'Healthcare'), ('Finanace', 'Finanace'), ('Agnostic', 'Agnostic'), ('HigherEducation', 'Higher Education')], default='Agnostic', max_length=100, null=True),
        ),
    ]
