# Generated by Django 3.2 on 2023-03-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0010_auto_20230325_0204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfpdata',
            old_name='document_ink',
            new_name='document_link',
        ),
        migrations.RenameField(
            model_name='rfpsection',
            old_name='document_Link',
            new_name='document_link',
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, choices=[('Finanace', 'Finanace'), ('HigherEducation', 'Higher Education'), ('Agnostic', 'Agnostic'), ('Healthcare', 'Healthcare')], default='Agnostic', max_length=100, null=True),
        ),
    ]
