# Generated by Django 3.2 on 2023-03-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0011_auto_20230326_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, choices=[('Healthcare', 'Healthcare'), ('Finanace', 'Finanace'), ('Agnostic', 'Agnostic'), ('HigherEducation', 'Higher Education')], default='Agnostic', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rfpdata',
            name='content_type',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rfpdata',
            name='country',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rfpdata',
            name='document_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rfpdata',
            name='image_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rfpdata',
            name='industry',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rfpdata',
            name='question',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rfpdata',
            name='rfp_resource_name',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rfpdata',
            name='rfpid',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rfpdata',
            name='section_data',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rfpsection',
            name='conten_type',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rfpsection',
            name='country',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rfpsection',
            name='document_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rfpsection',
            name='image_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rfpsection',
            name='industry',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rfpsection',
            name='question',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rfpsection',
            name='rfpid',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rfpsection',
            name='section_data',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rfpsection',
            name='sub_section',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
