# Generated by Django 4.1.7 on 2023-03-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0013_auto_20230326_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfpsection',
            name='conten_type',
        ),
        migrations.AddField(
            model_name='rfpsection',
            name='content_type',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, choices=[('Agnostic', 'Agnostic'), ('Finanace', 'Finanace'), ('Healthcare', 'Healthcare'), ('HigherEducation', 'Higher Education')], default='Agnostic', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rfpdata',
            name='content_type',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rfpdata',
            name='country',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rfpdata',
            name='document_link',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rfpdata',
            name='image_link',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rfpdata',
            name='industry',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rfpdata',
            name='question',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rfpdata',
            name='rfp_resource_name',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rfpdata',
            name='rfpid',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rfpdata',
            name='section_data',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rfpsection',
            name='country',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rfpsection',
            name='document_link',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rfpsection',
            name='image_link',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rfpsection',
            name='industry',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rfpsection',
            name='question',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rfpsection',
            name='rfpid',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rfpsection',
            name='section_data',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rfpsection',
            name='sub_section',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
