# Generated by Django 4.1.7 on 2023-03-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0014_remove_rfpsection_conten_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askques',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, choices=[('Healthcare', 'Healthcare'), ('HigherEducation', 'Higher Education'), ('Finanace', 'Finanace'), ('Agnostic', 'Agnostic')], default='Agnostic', max_length=100, null=True),
        ),
    ]
