# Generated by Django 4.1.7 on 2023-03-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0015_alter_askques_id_alter_image_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfpsection',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfpsection',
            name='user',
            field=models.ManyToManyField(blank=True, to='RFP.users'),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, choices=[('Healthcare', 'Healthcare'), ('Agnostic', 'Agnostic'), ('HigherEducation', 'Higher Education'), ('Finanace', 'Finanace')], default='Agnostic', max_length=100, null=True),
        ),
    ]
