# Generated by Django 4.1.7 on 2023-03-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0016_rfpsection_order_rfpsection_user_alter_image_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, choices=[('Agnostic', 'Agnostic'), ('Finanace', 'Finanace'), ('Healthcare', 'Healthcare'), ('HigherEducation', 'Higher Education')], default='Agnostic', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rfpdata',
            name='content_type',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rfpdata',
            name='country',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rfpdata',
            name='industry',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rfpdata',
            name='rfp_resource_name',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rfpdata',
            name='section_data',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rfpsection',
            name='content_type',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rfpsection',
            name='country',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rfpsection',
            name='industry',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rfpsection',
            name='section_data',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rfpsection',
            name='sub_section',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
