# Generated by Django 4.1.7 on 2023-03-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0017_alter_image_caption_alter_rfpdata_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_usercopy',
            name='file_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, choices=[('Healthcare', 'Healthcare'), ('HigherEducation', 'Higher Education'), ('Agnostic', 'Agnostic'), ('Finanace', 'Finanace')], default='Agnostic', max_length=100, null=True),
        ),
    ]
