# Generated by Django 4.1.7 on 2023-03-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0021_remove_rfpsection_row_type_rfpsection_country_matrix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='cloud_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, choices=[('Agnostic', 'Agnostic'), ('Finanace', 'Finanace'), ('HigherEducation', 'Higher Education'), ('Healthcare', 'Healthcare')], default='Agnostic', max_length=100, null=True),
        ),
    ]
