# Generated by Django 4.1.7 on 2023-03-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0022_image_cloud_link_alter_image_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_usercopy',
            name='matrix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, choices=[('Healthcare', 'Healthcare'), ('Agnostic', 'Agnostic'), ('HigherEducation', 'Higher Education'), ('Finanace', 'Finanace')], default='Agnostic', max_length=100, null=True),
        ),
    ]
