# Generated by Django 3.1.2 on 2023-04-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0023_document_usercopy_matrix_alter_image_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, choices=[('Australia', 'Australia'), ('UK', 'UK'), ('US', 'US')], default='Australia', max_length=100, null=True)),
                ('Industry', models.CharField(blank=True, choices=[('Healthcare', 'Healthcare'), ('HigherEducation', 'Higher Education'), ('Finanace', 'Finanace'), ('Agnostic', 'Agnostic')], default='Healthcare', max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='./media/')),
                ('selected', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, max_length=200, null=True)),
                ('clientgeo', models.CharField(blank=True, max_length=200, null=True)),
                ('picup', models.ImageField(upload_to='imgdir/')),
            ],
        ),
        migrations.DeleteModel(
            name='First_Page',
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, choices=[('Healthcare', 'Healthcare'), ('HigherEducation', 'Higher Education'), ('Finanace', 'Finanace'), ('Agnostic', 'Agnostic')], default='Agnostic', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='info',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kpmgadd',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='extraimage',
            name='user',
            field=models.ManyToManyField(blank=True, to='RFP.Users'),
        ),
    ]
