# Generated by Django 3.1.2 on 2023-04-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0024_auto_20230410_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssuptionAndRisk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, max_length=200, null=True)),
                ('clientgeo', models.CharField(blank=True, max_length=200, null=True)),
                ('Topic', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='Industry',
            field=models.CharField(blank=True, choices=[('Finanace', 'Finanace'), ('Agnostic', 'Agnostic'), ('Healthcare', 'Healthcare'), ('HigherEducation', 'Higher Education')], default='Healthcare', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='country',
            field=models.CharField(blank=True, choices=[('Australia', 'Australia'), ('US', 'US'), ('UK', 'UK')], default='Australia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, choices=[('Finanace', 'Finanace'), ('Agnostic', 'Agnostic'), ('Healthcare', 'Healthcare'), ('HigherEducation', 'Higher Education')], default='Agnostic', max_length=100, null=True),
        ),
    ]
