# Generated by Django 3.1.2 on 2023-04-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0025_auto_20230410_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='First_Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('industry', models.CharField(max_length=50)),
                ('pic1', models.ImageField(upload_to='First_page_upload/Manual')),
                ('pic2', models.ImageField(upload_to='First_page_upload/Manual')),
                ('pic3', models.ImageField(upload_to='First_page_upload/Manual')),
                ('options1', models.CharField(blank=True, max_length=10, null=True)),
                ('options2', models.CharField(blank=True, max_length=10, null=True)),
                ('options3', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='Industry',
            field=models.CharField(blank=True, choices=[('Agnostic', 'Agnostic'), ('Finanace', 'Finanace'), ('HigherEducation', 'Higher Education'), ('Healthcare', 'Healthcare')], default='Healthcare', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='country',
            field=models.CharField(blank=True, choices=[('Australia', 'Australia'), ('UK', 'UK'), ('US', 'US')], default='Australia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, choices=[('Agnostic', 'Agnostic'), ('Finanace', 'Finanace'), ('HigherEducation', 'Higher Education'), ('Healthcare', 'Healthcare')], default='Agnostic', max_length=100, null=True),
        ),
    ]
