# Generated by Django 3.1.2 on 2023-04-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0026_auto_20230410_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraimage',
            name='Industry',
            field=models.CharField(blank=True, choices=[('Healthcare', 'Healthcare'), ('Finanace', 'Finanace'), ('HigherEducation', 'Higher Education'), ('Agnostic', 'Agnostic')], default='Healthcare', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, choices=[('Healthcare', 'Healthcare'), ('Finanace', 'Finanace'), ('HigherEducation', 'Higher Education'), ('Agnostic', 'Agnostic')], default='Agnostic', max_length=100, null=True),
        ),
    ]
