# Generated by Django 3.1.2 on 2023-04-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0027_auto_20230410_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assuptionandrisk',
            name='clientgeo',
        ),
        migrations.AddField(
            model_name='assuptionandrisk',
            name='country',
            field=models.CharField(blank=True, choices=[('US', 'US'), ('UK', 'UK'), ('Australia', 'Australia')], default='Australia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assuptionandrisk',
            name='Topic',
            field=models.CharField(blank=True, choices=[('Assuption_And_Risk', 'Assuption_And_Risk'), ('Key_consideration_and_risk', 'Key_consideration_and_risk')], default='Assuption_And_Risk', max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='assuptionandrisk',
            name='user',
        ),
        migrations.AddField(
            model_name='assuptionandrisk',
            name='user',
            field=models.ManyToManyField(blank=True, to='RFP.Users'),
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='Industry',
            field=models.CharField(blank=True, choices=[('Agnostic', 'Agnostic'), ('HigherEducation', 'Higher Education'), ('Finanace', 'Finanace'), ('Healthcare', 'Healthcare')], default='Healthcare', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='country',
            field=models.CharField(blank=True, choices=[('US', 'US'), ('UK', 'UK'), ('Australia', 'Australia')], default='Australia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, choices=[('Agnostic', 'Agnostic'), ('HigherEducation', 'Higher Education'), ('Finanace', 'Finanace'), ('Healthcare', 'Healthcare')], default='Agnostic', max_length=100, null=True),
        ),
    ]
