# Generated by Django 3.1.2 on 2023-04-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0028_auto_20230410_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='assuptionandrisk',
            name='Description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='assuptionandrisk',
            name='Topic',
            field=models.CharField(blank=True, choices=[('Key_consideration_and_risk', 'Key_consideration_and_risk'), ('Assuption_And_Risk', 'Assuption_And_Risk')], default='Assuption_And_Risk', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assuptionandrisk',
            name='country',
            field=models.CharField(blank=True, choices=[('Australia', 'Australia'), ('US', 'US'), ('UK', 'UK')], default='Australia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='Industry',
            field=models.CharField(blank=True, choices=[('HigherEducation', 'Higher Education'), ('Agnostic', 'Agnostic'), ('Healthcare', 'Healthcare'), ('Finanace', 'Finanace')], default='Healthcare', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='country',
            field=models.CharField(blank=True, choices=[('Australia', 'Australia'), ('US', 'US'), ('UK', 'UK')], default='Australia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, choices=[('HigherEducation', 'Higher Education'), ('Agnostic', 'Agnostic'), ('Healthcare', 'Healthcare'), ('Finanace', 'Finanace')], default='Agnostic', max_length=100, null=True),
        ),
    ]
