# Generated by Django 3.1.2 on 2023-04-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0029_auto_20230410_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assuptionandrisk',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assuptionandrisk',
            name='Topic',
            field=models.CharField(blank=True, choices=[('Assuption_And_Risk', 'Assuption_And_Risk'), ('Key_consideration_and_risk', 'Key_consideration_and_risk')], default='Assuption_And_Risk', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assuptionandrisk',
            name='country',
            field=models.CharField(blank=True, choices=[('US', 'US'), ('Australia', 'Australia'), ('UK', 'UK')], default='Australia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='Industry',
            field=models.CharField(blank=True, choices=[('Finanace', 'Finanace'), ('Healthcare', 'Healthcare'), ('Agnostic', 'Agnostic'), ('HigherEducation', 'Higher Education')], default='Healthcare', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='country',
            field=models.CharField(blank=True, choices=[('US', 'US'), ('Australia', 'Australia'), ('UK', 'UK')], default='Australia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, choices=[('Finanace', 'Finanace'), ('Healthcare', 'Healthcare'), ('Agnostic', 'Agnostic'), ('HigherEducation', 'Higher Education')], default='Agnostic', max_length=100, null=True),
        ),
    ]
