# Generated by Django 3.1.2 on 2023-04-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0030_auto_20230410_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assuptionandrisk',
            name='country',
            field=models.CharField(blank=True, choices=[('US', 'US'), ('UK', 'UK'), ('Australia', 'Australia')], default='Australia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='Industry',
            field=models.CharField(blank=True, choices=[('Finanace', 'Finanace'), ('Agnostic', 'Agnostic'), ('HigherEducation', 'Higher Education'), ('Healthcare', 'Healthcare')], default='Healthcare', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='country',
            field=models.CharField(blank=True, choices=[('US', 'US'), ('UK', 'UK'), ('Australia', 'Australia')], default='Australia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, choices=[('Finanace', 'Finanace'), ('Agnostic', 'Agnostic'), ('HigherEducation', 'Higher Education'), ('Healthcare', 'Healthcare')], default='Agnostic', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SectionExtraImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, choices=[('US', 'US'), ('UK', 'UK'), ('Australia', 'Australia')], default='Australia', max_length=100, null=True)),
                ('Industry', models.CharField(blank=True, choices=[('Finanace', 'Finanace'), ('Agnostic', 'Agnostic'), ('HigherEducation', 'Higher Education'), ('Healthcare', 'Healthcare')], default='Healthcare', max_length=100, null=True)),
                ('Section', models.CharField(blank=True, choices=[('Our Approach to Leadership Alignment', 'Our Approach to Leadership Alignment'), ('Implementation Timeline', 'Implementation Timeline'), ('Your Transformation Journey', 'Your Transformation Journey'), ('Data Migration (Powered Data)', 'Data Migration (Powered Data)'), ('Our Approach to Change Management', 'Our Approach to Change Management'), ('Appendix 2 - Additional Change Management & Training Services', 'Appendix 2 - Additional Change Management & Training Services'), ('Our Approach to Cultural Change', 'Our Approach to Cultural Change'), ('Appendix 4 - Project Team Roles and Responsibilities', 'Appendix 4 - Project Team Roles and Responsibilities'), ('KPMG Powered Enterprise', 'KPMG Powered Enterprise'), ('Pricing', 'Pricing'), ('Our Approach to developing a communications plan', 'Our Approach to developing a communications plan'), ('Executive Summary', 'Executive Summary'), ('Appendix 5 - KPMG Powered Innovation (Cyber, Lighthouse)', 'Appendix 5 - KPMG Powered Innovation (Cyber, Lighthouse)'), ('Appendix 1 - Company Profile', 'Appendix 1 - Company Profile'), ('Appendix 3 - Data Migration Approach', 'Appendix 3 - Data Migration Approach'), ('Key Considerations and Risks', 'Key Considerations and Risks'), ('Appendix 6 - KPMG Thought Leadership', 'Appendix 6 - KPMG Thought Leadership'), ('Appendix 6 - KPMG ThinkPay', 'Appendix 6 - KPMG ThinkPay'), ('Our Deployment Methodology', 'Our Deployment Methodology'), ('Our Approach to Training', 'Our Approach to Training'), ('Assumptions', 'Assumptions'), ('Functional Scope', 'Functional Scope'), ('Our Deployment Approach', 'Our Deployment Approach'), ('Project Team Structure', 'Project Team Structure'), ('Our Integration Approach', 'Our Integration Approach'), ('Our Approach to developing Change Impact Assessments', 'Our Approach to developing Change Impact Assessments'), ('Demonstrated Capability and Capacity', 'Demonstrated Capability and Capacity')], default='Executive Summary', max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='./media/')),
                ('selected', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.ManyToManyField(blank=True, to='RFP.Users')),
            ],
        ),
    ]
