# Generated by Django 3.1.2 on 2023-04-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0031_auto_20230414_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assuptionandrisk',
            name='country',
            field=models.CharField(blank=True, choices=[('Australia', 'Australia'), ('US', 'US'), ('UK', 'UK')], default='Australia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='Industry',
            field=models.CharField(blank=True, choices=[('Agnostic', 'Agnostic'), ('Healthcare', 'Healthcare'), ('Finanace', 'Finanace'), ('HigherEducation', 'Higher Education')], default='Healthcare', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='country',
            field=models.CharField(blank=True, choices=[('Australia', 'Australia'), ('US', 'US'), ('UK', 'UK')], default='Australia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, choices=[('Agnostic', 'Agnostic'), ('Healthcare', 'Healthcare'), ('Finanace', 'Finanace'), ('HigherEducation', 'Higher Education')], default='Agnostic', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sectionextraimage',
            name='Industry',
            field=models.CharField(blank=True, choices=[('Agnostic', 'Agnostic'), ('Healthcare', 'Healthcare'), ('Finanace', 'Finanace'), ('HigherEducation', 'Higher Education')], default='Healthcare', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sectionextraimage',
            name='Section',
            field=models.CharField(blank=True, choices=[('Executive Summary', 'Executive Summary'), ('Our Approach to Leadership Alignment', 'Our Approach to Leadership Alignment'), ('Appendix 6 - KPMG ThinkPay', 'Appendix 6 - KPMG ThinkPay'), ('Functional Scope', 'Functional Scope'), ('Implementation Timeline', 'Implementation Timeline'), ('Our Approach to developing a communications plan', 'Our Approach to developing a communications plan'), ('Project Team Structure', 'Project Team Structure'), ('Assumptions', 'Assumptions'), ('Appendix 4 - Project Team Roles and Responsibilities', 'Appendix 4 - Project Team Roles and Responsibilities'), ('Our Deployment Approach', 'Our Deployment Approach'), ('Our Deployment Methodology', 'Our Deployment Methodology'), ('Appendix 6 - KPMG Thought Leadership', 'Appendix 6 - KPMG Thought Leadership'), ('Our Approach to Cultural Change', 'Our Approach to Cultural Change'), ('Pricing', 'Pricing'), ('KPMG Powered Enterprise', 'KPMG Powered Enterprise'), ('Our Approach to Training', 'Our Approach to Training'), ('Our Approach to Change Management', 'Our Approach to Change Management'), ('Your Transformation Journey', 'Your Transformation Journey'), ('Data Migration (Powered Data)', 'Data Migration (Powered Data)'), ('Appendix 2 - Additional Change Management & Training Services', 'Appendix 2 - Additional Change Management & Training Services'), ('Our Approach to developing Change Impact Assessments', 'Our Approach to developing Change Impact Assessments'), ('Appendix 5 - KPMG Powered Innovation (Cyber, Lighthouse)', 'Appendix 5 - KPMG Powered Innovation (Cyber, Lighthouse)'), ('Appendix 3 - Data Migration Approach', 'Appendix 3 - Data Migration Approach'), ('Demonstrated Capability and Capacity', 'Demonstrated Capability and Capacity'), ('Appendix 1 - Company Profile', 'Appendix 1 - Company Profile'), ('Our Integration Approach', 'Our Integration Approach'), ('Key Considerations and Risks', 'Key Considerations and Risks')], default='Executive Summary', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sectionextraimage',
            name='country',
            field=models.CharField(blank=True, choices=[('Australia', 'Australia'), ('US', 'US'), ('UK', 'UK')], default='Australia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sectionextraimage',
            name='image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
