# Generated by Django 4.1.7 on 2023-04-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0031_alter_assuptionandrisk_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assuptionandrisk',
            name='Topic',
            field=models.CharField(blank=True, choices=[('Key_consideration_and_risk', 'Key_consideration_and_risk'), ('Assuption_And_Risk', 'Assuption_And_Risk')], default='Assuption_And_Risk', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assuptionandrisk',
            name='country',
            field=models.CharField(blank=True, choices=[('Australia', 'Australia'), ('UK', 'UK'), ('US', 'US')], default='Australia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='Industry',
            field=models.CharField(blank=True, choices=[('HigherEducation', 'Higher Education'), ('Finanace', 'Finanace'), ('Agnostic', 'Agnostic'), ('Healthcare', 'Healthcare')], default='Healthcare', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='country',
            field=models.CharField(blank=True, choices=[('Australia', 'Australia'), ('UK', 'UK'), ('US', 'US')], default='Australia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, choices=[('HigherEducation', 'Higher Education'), ('Finanace', 'Finanace'), ('Agnostic', 'Agnostic'), ('Healthcare', 'Healthcare')], default='Agnostic', max_length=100, null=True),
        ),
    ]
