# Generated by Django 3.1.2 on 2023-04-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0032_auto_20230414_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assuptionandrisk',
            name='country',
            field=models.CharField(blank=True, choices=[('US', 'US'), ('UK', 'UK'), ('Australia', 'Australia')], default='Australia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='Industry',
            field=models.CharField(blank=True, choices=[('Finanace', 'Finanace'), ('Agnostic', 'Agnostic'), ('HigherEducation', 'Higher Education'), ('Healthcare', 'Healthcare')], default='Healthcare', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='country',
            field=models.CharField(blank=True, choices=[('US', 'US'), ('UK', 'UK'), ('Australia', 'Australia')], default='Australia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, choices=[('Finanace', 'Finanace'), ('Agnostic', 'Agnostic'), ('HigherEducation', 'Higher Education'), ('Healthcare', 'Healthcare')], default='Agnostic', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sectionextraimage',
            name='Industry',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sectionextraimage',
            name='Section',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sectionextraimage',
            name='country',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
