# Generated by Django 4.1.7 on 2023-04-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0033_document_usercopy_rfp_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RfpDocuments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=50)),
                ('user', models.CharField(blank=True, max_length=200)),
                ('rfp_file', models.FileField(blank=True, null=True, upload_to='files/rfp_documents')),
            ],
        ),
        migrations.AlterField(
            model_name='assuptionandrisk',
            name='Topic',
            field=models.CharField(blank=True, choices=[('Assuption_And_Risk', 'Assuption_And_Risk'), ('Key_consideration_and_risk', 'Key_consideration_and_risk')], default='Assuption_And_Risk', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assuptionandrisk',
            name='country',
            field=models.CharField(blank=True, choices=[('US', 'US'), ('Australia', 'Australia'), ('UK', 'UK')], default='Australia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='Industry',
            field=models.CharField(blank=True, choices=[('Healthcare', 'Healthcare'), ('Agnostic', 'Agnostic'), ('Finanace', 'Finanace'), ('HigherEducation', 'Higher Education')], default='Healthcare', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='country',
            field=models.CharField(blank=True, choices=[('US', 'US'), ('Australia', 'Australia'), ('UK', 'UK')], default='Australia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, choices=[('Healthcare', 'Healthcare'), ('Agnostic', 'Agnostic'), ('Finanace', 'Finanace'), ('HigherEducation', 'Higher Education')], default='Agnostic', max_length=100, null=True),
        ),
    ]
