# Generated by Django 3.1.2 on 2023-04-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0033_auto_20230414_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionextraimage',
            old_name='Section',
            new_name='image_link',
        ),
        migrations.RenameField(
            model_name='sectionextraimage',
            old_name='image',
            new_name='section_data',
        ),
        migrations.AlterField(
            model_name='assuptionandrisk',
            name='Topic',
            field=models.CharField(blank=True, choices=[('Key_consideration_and_risk', 'Key_consideration_and_risk'), ('Assuption_And_Risk', 'Assuption_And_Risk')], default='Assuption_And_Risk', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='Industry',
            field=models.CharField(blank=True, choices=[('Finanace', 'Finanace'), ('HigherEducation', 'Higher Education'), ('Agnostic', 'Agnostic'), ('Healthcare', 'Healthcare')], default='Healthcare', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, choices=[('Finanace', 'Finanace'), ('HigherEducation', 'Higher Education'), ('Agnostic', 'Agnostic'), ('Healthcare', 'Healthcare')], default='Agnostic', max_length=100, null=True),
        ),
    ]
