# Generated by Django 3.1.2 on 2023-04-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0034_auto_20230414_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionextraimage',
            old_name='Industry',
            new_name='industry',
        ),
        migrations.AlterField(
            model_name='assuptionandrisk',
            name='country',
            field=models.CharField(blank=True, choices=[('Australia', 'Australia'), ('UK', 'UK'), ('US', 'US')], default='Australia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='Industry',
            field=models.CharField(blank=True, choices=[('Agnostic', 'Agnostic'), ('HigherEducation', 'Higher Education'), ('Finanace', 'Finanace'), ('Healthcare', 'Healthcare')], default='Healthcare', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='country',
            field=models.CharField(blank=True, choices=[('Australia', 'Australia'), ('UK', 'UK'), ('US', 'US')], default='Australia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, choices=[('Agnostic', 'Agnostic'), ('HigherEducation', 'Higher Education'), ('Finanace', 'Finanace'), ('Healthcare', 'Healthcare')], default='Agnostic', max_length=100, null=True),
        ),
    ]
