# Generated by Django 4.1.7 on 2023-04-18 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0036_rfpdocuments_alter_assuptionandrisk_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfpsection',
            name='document_file_name',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
