# Generated by Django 4.1 on 2023-04-27 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("RFP", "0037_document_usercopy_rfp_section_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="notsatisfieddoc",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user", models.CharField(blank=True, max_length=200, null=True)),
                ("clientgeo", models.CharField(
                    blank=True, max_length=200, null=True)),
                ("docup", models.ImageField(upload_to="notsatisfieddoc/")),
                ("query", models.TextField(blank=True, null=True)),
            ],
        ),

    ]
