# Generated by Django 4.1.7 on 2023-04-26 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0037_document_usercopy_rfp_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDocumentUsercopy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_doc', models.FileField(blank=True, null=True, upload_to='files/rfp_image_documents')),
                ('doc_user_copy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RFP.document_usercopy')),
            ],
        ),
    ]
