# Generated by Django 4.1 on 2023-05-06 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("RFP", "0038_document_usercopy_rfp_section_and_more"),
        ("RFP", "0038_notsatisfieddoc_document_usercopy_rfp_section_and_more"),
    ]

    operations = []
