# Generated by Django 4.1 on 2023-05-06 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("RFP", "0039_merge_20230506_1244"),
    ]

    operations = [

        migrations.CreateModel(
            name="clientlogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UK", "UK"),
                            ("US", "US"),
                            ("Australia", "Australia"),
                        ],
                        default="Australia",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "Industry",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HigherEducation", "Higher Education"),
                            ("Healthcare", "Healthcare"),
                            ("Finanace", "Finanace"),
                            ("Agnostic", "Agnostic"),
                        ],
                        default="Healthcare",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="./media/clientlogo/"
                    ),
                ),
                ("selected", models.CharField(blank=True, max_length=10, null=True)),
                ("user", models.ManyToManyField(blank=True, to="RFP.users")),
            ],
        ),
    ]
