# Generated by Django 4.1 on 2023-05-08 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("RFP", "0041_logoupload_document_usercopy_rfp_section_and_more"),
    ]

    operations = [

        migrations.AddField(
            model_name="imageupload",
            name="approved",
            field=models.CharField(
                blank=True, default="No", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="logoupload",
            name="approved",
            field=models.CharField(
                blank=True, default="No", max_length=200, null=True),
        )
    ]
