# Generated by Django 4.1 on 2023-05-10 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("RFP", "0042_document_usercopy_rfp_section_imageupload_approved_and_more"),
    ]

    operations = [

        migrations.AddField(
            model_name="kpmgadd",
            name="fulladdress",
            field=models.TextField(blank=True, null=True),
        ),

    ]
