# Generated by Django 4.1 on 2023-05-10 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("RFP", "0043_document_usercopy_rfp_section_kpmgadd_fulladdress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assuptionandrisk",
            name="file_link",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),

    ]
