# Generated by Django 4.1 on 2023-05-10 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("RFP", "0044_assuptionandrisk_file_link_and_more"),
    ]

    operations = [

        migrations.AlterField(
            model_name="assuptionandrisk",
            name="Topic",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Workday", "Workday"),
                    ("Covid-19", "Covid-19"),
                    ("Software", "Software"),
                    ("Change Management", "Change Management"),
                    ("Testing", "Testing"),
                    ("Deployment and Support", "Deployment and Support"),
                    ("Data Migration", "Data Migration"),
                    ("Integration", "Integration"),
                    ("General", "General"),
                    ("Resources", "Resources"),
                ],
                default="General",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="assuptionandrisk",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[("UK", "UK"), ("US", "US"), ("AU", "AU")],
                default="AU",
                max_length=100,
                null=True,
            ),
        ),

    ]
