# Generated by Django 4.1 on 2023-05-21 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("RFP", "0049_rename_document_link_assuptionandrisk_document_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="userextraimage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user", models.CharField(blank=True, max_length=200, null=True)),
                ("country", models.CharField(blank=True, max_length=200, null=True)),
                ("industry", models.CharField(blank=True, max_length=200, null=True)),
                ("image", models.FileField(blank=True, null=True, upload_to="media/")),
            ],
        )
    ]
