# Generated by Django 4.1 on 2023-05-21 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("RFP", "0050_userextraimage_userriskandassumption_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="userriskandassumption",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user", models.CharField(blank=True, max_length=200, null=True)),
                ("country", models.CharField(blank=True, max_length=200, null=True)),
                ("industry", models.CharField(blank=True, max_length=200, null=True)),
                ("section", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "approved",
                    models.CharField(
                        blank=True, default="No", max_length=200, null=True
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userextraimage",
            name="approved",
            field=models.CharField(
                blank=True, default="No", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="userquestionans",
            name="approved",
            field=models.CharField(
                blank=True, default="No", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="userstandardsection",
            name="approved",
            field=models.CharField(
                blank=True, default="No", max_length=200, null=True),
        ),
    ]
