# Generated by Django 4.1 on 2023-05-23 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("RFP", "0051_userriskandassumption_document_usercopy_rfp_section_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Uploadassumprisk",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user", models.CharField(blank=True, max_length=200, null=True)),
                ("clientname", models.CharField(
                    blank=True, max_length=200, null=True)),
                ("clientgeo", models.CharField(
                    blank=True, max_length=200, null=True)),
                ("picup", models.ImageField(upload_to="./media/")),
                (
                    "approved",
                    models.CharField(
                        blank=True, default="No", max_length=200, null=True
                    ),
                ),
            ],
        )
    ]
