# Generated by Django 4.1 on 2023-05-23 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("RFP", "0052_uploadassumprisk_document_usercopy_rfp_section_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="Uploadassumprisk",),

    ]
