# Generated by Django 4.1 on 2023-05-24 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("RFP", "0053_delete_uploadassumprisk_and_more"),
    ]

    operations = [
        
        migrations.AddField(
            model_name="logoupload",
            name="industry",
            field=models.CharField(blank=True, max_length=200, null=True),
        )
    ]
