# Generated by Django 4.1 on 2023-05-26 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("RFP", "0054_document_usercopy_rfp_section_logoupload_industry_and_more"),
    ]

    operations = [

        migrations.AddField(
            model_name="logoupload",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userextraimage",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userquestionans",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userriskandassumption",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userstandardsection",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),

    ]
