# Generated by Django 4.1 on 2023-06-13 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("RFP", "0055_document_usercopy_rfp_section_logoupload_feedback_and_more"),
    ]

    operations = [
        
        migrations.AddField(
            model_name="kpmggeo",
            name="displayKPMGgeo",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        
    ]
