# Generated by Django 4.1 on 2023-06-15 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("RFP", "0056_document_usercopy_rfp_section_kpmggeo_displaykpmggeo_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="image", name="image",),
        
        migrations.AddField(
            model_name="image",
            name="image_link",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        
    ]
