# Generated by Django 4.1 on 2023-06-15 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("RFP", "0057_remove_image_image_document_usercopy_rfp_section_and_more"),
    ]

    operations = [
        
        
        migrations.AlterField(
            model_name="image",
            name="caption",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Higher Education", "Education"),
                    ("Transportation", "Transportation"),
                    ("Retail", "Retail"),
                    ("Energy", "Energy"),
                    ("Healthcare", "Healthcare"),
                    ("Agnostic", "Agnostic"),
                    ("Manufacturing", "Manufacturing"),
                    ("Finanace", "Finanace"),
                ],
                default="Agnostic",
                max_length=100,
                null=True,
            ),
        ),
        
    ]
