# Generated by Django 4.1 on 2023-07-03 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("RFP", "0057_auto_20230614_1532"),
        ("RFP", "0058_document_usercopy_rfp_section_image_title_and_more"),
    ]

    operations = []
