# Generated by Django 4.1 on 2023-07-03 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("RFP", "0059_merge_20230703_1143"),
    ]

    operations = [

        migrations.AddField(
            model_name="image",
            name="image_upload",
            field=models.FileField(
                blank=True, null=True, upload_to="./media/image_upload/"
            ),
        ),

    ]
