# Fetching the latest nginx image
# FROM nginx:1.23-alpine
FROM nginx:1.21.0

# # Removing default nginx.conf
# RUN rm /etc/nginx/conf.d/default.conf
RUN rm /etc/nginx/conf.d/*
RUN rm /etc/nginx/nginx.conf


# # Copying our nginx.conf
COPY nginx.conf /etc/nginx/
COPY default.conf /etc/nginx/conf.d/
EXPOSE 80 443